# Restrict the number of private warps each player can have
# - If a player has the `mcmewarps.limits.ignore.private` permission the limit is ignored
warp-name-max-length: 64

private-warp-limits:
  default-limit: 2
  configured:
#    adventurer: 10
#    commoner: 50

# This list is used for the setLayer command and it should align with the
# layers configured in the paper config.yml
layer-keys:
  - major

#sql:
#  user:
#  password:
#  db-name:
#  ip:
#  port: