# Restrict the number of private warps each player can have
# - If a player has the `mcmewarps.limits.ignore.private` permission the limit is ignored
private-warp-limit: 25
warp-name-max-length: 64

#sql:
#  user:
#  password:
#  dbName:
#  ip:
#  port: